### ISSUE TITLE
newest bugs after update // voice announcements by distance not working

### ISSUE THREAD

**Issue by RedRainHag** [OpenTracksApp/OpenTracks#722]
- can't export my runs anymore. I get the message that their was an error for all the exports...
- I was using voice announcements for every 5km but it kept on announcing without pause. So I had to turn off the announcements.
- downgrade to older version viva Fdroid always resulted in an error that the installation was aborted.
- app crashed several times after the update to 3.17, 

Thank you for your good work!

**Comment by dennisguse** [comment]
Yes, the v3.17-series has some issue that we missed before release.

>     * can't export my runs anymore. I get the message that their was an error for all the exports...

Don't know what the issue is; can share some more infos (best case logcat).

> 
>     * I was using voice announcements for every 5km but it kept on announcing without pause. So I had to turn off the announcements. 

Tracked as #721; it is fixed and released as v3.17.3.
As of today, this is not yet available via F-Droid.

> 
>     * downgrade to older version viva Fdroid always resulted in an error that the installation was aborted.

Do you have some error message for this?
Because it should be possible; not database changes were included.
So, it should just work...

>     * app crashed several times after the update to 3.17,

Best guess is #719.
Also partly affected #721.
We are working on it.

> 
> 
> Thank you for your good work!
Thanks!

**Comment by RedRainHag** [comment]
Thanks for the reply! 

> Do you have some error message for this?

To the downgrade I can't tell you much, I just get the message from F-Droid that the installation was aborted due to an unknown error and thats it.. 

> Don't know what the issue is; can share some more infos (best case logcat).
where can I get to the logcat? Not sure if that one still exists since I deinstalled and reinstalled the program after that...

**Comment by dennisguse** [comment]
@RedRainHag
regarding logcat.
You need to enable developer mode on your device: https://developer.android.com/studio/debug/dev-options
And then you can use AndroidStudio to get the logcat: https://developer.android.com/studio/debug/am-logcat

**Comment by Fregf** [comment]
> > * I was using voice announcements for every 5km but it kept on announcing without pause. So I had to turn off the announcements. 
> > ```
> 
> Tracked as #721; it is fixed and released as ~v3.17.3~ v3.17.2.
> As of today, this is not yet available via F-Droid.

This bug is still present for me in 3.17.3 currently in f-droid: I have it set to give announcements every 1 km, but it was constantly announcing.

**Comment by dennisguse** [comment]
@Fregf by just a quick look: yes that might be broken as well due to the distance refactoring.
I will check this during the week; it will take some time as we have very little test coverage for the announcements.

**Comment by dennisguse** [comment]
Released in v3.18.0
